[2025-07-05T19:23:24.285+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T19:23:24.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2023-01-21T00:00:00+00:00 [queued]>
[2025-07-05T19:23:24.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2023-01-21T00:00:00+00:00 [queued]>
[2025-07-05T19:23:24.333+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-05T19:23:24.347+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2023-01-21 00:00:00+00:00
[2025-07-05T19:23:24.357+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8453) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T19:23:24.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2023-01-21T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmp2_vh1v3p']
[2025-07-05T19:23:24.358+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask transform
[2025-07-05T19:23:24.358+0000] {standard_task_runner.py:63} INFO - Started process 8464 to run task
[2025-07-05T19:23:24.417+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2023-01-21T00:00:00+00:00 [running]> on host 20adb53d65c4
[2025-07-05T19:23:24.513+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-21T00:00:00+00:00'
[2025-07-05T19:23:24.515+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T19:23:24.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T19:23:24.516+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cotacoes.py", line 52, in transform
    cotacoes = kwargs['ti'].xcom_pull(task_id='extract')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-05T19:23:24.527+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2023-01-21T00:00:00+00:00, execution_date=20230121T000000, start_date=20250705T192324, end_date=20250705T192324
[2025-07-05T19:23:24.539+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task transform (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 8464)
[2025-07-05T19:23:24.576+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T19:23:24.587+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
